stages:
  - test

# Based off https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/PHP.gitlab-ci.yml
php7.4-unit-test-job:
  stage: test
  image: php:7.4-cli-alpine
  before_script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - vendor/bin/phpunit --coverage-text --colors=never --testsuite unit-test

# Based off https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/PHP.gitlab-ci.yml
php8.1-unit-test-job:
  stage: test
  image: php:8.1-cli-alpine
  before_script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - vendor/bin/phpunit --coverage-text --colors=never --testsuite unit-test
