stages:
  - test
  - release

.php8.0:
  image: php:8.0-cli-alpine
  before_script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

.php8.2:
  image: php:8.2-cli-alpine
  before_script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar update # Run composer update here to update components to the latest PHP version

composer-outdated:
  extends: .php8.0
  stage: test
  script:
    - php composer.phar outdated --direct --strict

# Based off https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/PHP.gitlab-ci.yml
php8.0-unit-test:
  extends: .php8.0
  stage: test
  script:
    - vendor/bin/phpunit --coverage-text --colors=never --testsuite unitTest

# Based off https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/PHP.gitlab-ci.yml
php8.2-unit-test:
  extends: .php8.2
  stage: test
  script:
    - vendor/bin/phpunit --coverage-text --colors=never --testsuite unitTest

# Based off https://phpinsights.com/continuous-integration.html#gitlab-code-quality
phpinsights:
  extends:
    - .php8.0
  stage: test
  script:
    - vendor/bin/phpinsights -n --min-quality=95 --min-complexity=90 --min-architecture=95 --min-style=95 --ansi --format=codeclimate > codeclimate-report.json
  artifacts:
    reports:
      codequality: codeclimate-report.json

# Based off https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/gitlab-ci.md
semantic-release:
  stage: release
  image: node
  only:
    - main
  before_script:
    - npm install
  script:
    - npx semantic-release